version: '3'
services:
  # Redis Master Nodes
  redis-master-1:
    container_name: redis-master-1
    image: redis
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis-master-1.conf:/etc/redis.conf
      - ./data/redis-1/1:/data
    restart: always
    ports:
      - 7001:7001
    expose:
      - 17001 # Cluster Bus용 포트

  redis-master-2:
    container_name: redis-master-2
    image: redis
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis-master-2.conf:/etc/redis.conf
      - ./data/redis-2/1:/data
    restart: always
    ports:
      - 7002:7002
      - 17002:17002
    expose:
      - 17002

  redis-master-3:
    container_name: redis-master-3
    image: redis
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis-master-3.conf:/etc/redis.conf
      - ./data/redis-3/1:/data
    restart: always
    ports:
      - 7003:7003
    expose:
      - 17003

  # Redis Slave Nodes
  redis-slave-1:
    container_name: redis-slave-1
    image: redis
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis-slave-1.conf:/etc/redis.conf
      - ./data/redis-1/2:/data
    restart: always
    ports:
      - 7101:7101
    expose:
      - 17101

  redis-slave-2:
    container_name: redis-slave-2
    image: redis
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis-slave-2.conf:/etc/redis.conf
      - ./data/redis-2/2:/data
    restart: always
    ports:
      - 7102:7102
    expose:
      - 17102

  redis-slave-3:
    container_name: redis-slave-3
    image: redis
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis-slave-3.conf:/etc/redis.conf
      - ./data/redis-3/2:/data
    restart: always
    ports:
      - 7103:7103
    expose:
      - 17103

  # Redis Exporter (각 Redis 인스턴스별로 Exporter 추가)
  redis-exporter-master-1:
    container_name: redis-exporter-master-1
    image: oliver006/redis_exporter
    environment:
      - REDIS_ADDR=redis-master-1:7001
    expose:
      - 9121
    restart: always
    depends_on:
      - redis-master-1

  redis-exporter-master-2:
    container_name: redis-exporter-master-2
    image: oliver006/redis_exporter
    environment:
      - REDIS_ADDR=redis-master-2:7002
    expose:
      - 9121
    restart: always
    depends_on:
      - redis-master-2

  redis-exporter-master-3:
    container_name: redis-exporter-master-3
    image: oliver006/redis_exporter
    environment:
      - REDIS_ADDR=redis-master-3:7003
    expose:
      - 9121
    restart: always
    depends_on:
      - redis-master-3

  redis-exporter-slave-1:
    container_name: redis-exporter-slave-1
    image: oliver006/redis_exporter
    environment:
      - REDIS_ADDR=redis-slave-1:7101
    expose:
      - 9121
    restart: always
    depends_on:
      - redis-slave-1

  redis-exporter-slave-2:
    container_name: redis-exporter-slave-2
    image: oliver006/redis_exporter
    environment:
      - REDIS_ADDR=redis-slave-2:7102
    expose:
      - 9121
    restart: always
    depends_on:
      - redis-slave-2

  redis-exporter-slave-3:
    container_name: redis-exporter-slave-3
    image: oliver006/redis_exporter
    environment:
      - REDIS_ADDR=redis-slave-3:7103
    expose:
      - 9121
    restart: always
    depends_on:
      - redis-slave-3

  # Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./mornitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    ports:
      - 9090:9090
    restart: always
    depends_on:
      - redis-exporter-master-1
      - redis-exporter-master-2
      - redis-exporter-master-3
      - redis-exporter-slave-1
      - redis-exporter-slave-2
      - redis-exporter-slave-3

  # Grafana
  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=natel-discrete-panel  # 상태 전환 모니터링을 위한 수평 그래프 플러그인
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./mornitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./mornitoring/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - prometheus