global:
  scrape_interval: 15s  # 15초마다 수집

scrape_configs:
  - job_name: 'redis-cluster'
    static_configs:
      - targets:
          - 'redis-exporter-master-1:9121'
          - 'redis-exporter-master-2:9121'
          - 'redis-exporter-master-3:9121'
          - 'redis-exporter-slave-1:9121'
          - 'redis-exporter-slave-2:9121'
          - 'redis-exporter-slave-3:9121'
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):9121'
        target_label: instance
        replacement: '$1'
