{
 "title": "Redis Cluster 대시보드",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "label_values(redis_up, job)" }
  ]
 },
 "panels": [
  {
   "title": "각 노드에 저장된 항목 수",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_db_keys{job=\"$cluster\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "전체 노드가 정상 운영된 누적 시간",
   "type": "stat",
   "description": "노드 uptime의 최솟값",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(redis_uptime_in_seconds{job=\"$cluster\"}) / 3600"
    }
   ]
  },
  {
   "title": "클러스터 상태",
   "type": "status-history",
   "description": "초록색: 현재 마스터\n하늘색: 현재 레플리카\n\n레이블의 master/slave는 최초 클러스터 구성시의 정보일 뿐, \n\n현재 master/slave정보와 일치하지 않을 수 있음",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum((redis_instance_info{role=\"master\"} * 1) or (redis_instance_info{role=\"slave\"} * 0)) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "마스터별 연결된 슬레이브 개수",
   "type": "stat",
   "description": "0인 경우, 마스터 다운시 해당 슬롯 접근 불가",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_connected_slaves{job=\"$cluster\"}\n* on(instance) group_left(role) redis_instance_info{role=\"master\", job=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "초당 평균 처리율",
   "type": "timeseries",
   "description": "초당 평균 처리율",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{job=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "상위 5개 명령어의 초당 실행 횟수",
   "type": "timeseries",
   "description": "실행횟수 상위 5개 명령어 초당 실행 횟수",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{job=\"$cluster\"} [1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Fragment",
   "type": "timeseries",
   "description": "RSS - Used Memory\n\n노드별 Fragment를 나타냄",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(redis_memory_used_rss_bytes) by (instance) - sum(redis_memory_used_bytes) by (instance)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{job=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}}-input"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{job=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}}-output"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "description": "평균적으로 Expired/Eviction되는 수 (5분단위)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{job=\"$cluster\"}[5m])) by (addr)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{job=\"$cluster\"}[5m])) by (addr)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "전체 항목 수 / 만료되지 않는 항목 수",
   "type": "timeseries",
   "description": "만료 시간이 설정되지 않은 항목 수",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{job=\"$cluster\"}) - sum (redis_db_keys_expiring{job=\"$cluster\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{job=\"$cluster\"}) ",
     "legendFormat": "expiring"
    }
   ]
  }
 ]
}